#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'git'
cookbook 'erlang'
cookbook 'linc',
   :path => 'site-cookbooks/linc'
cookbook 'xfce4'
cookbook 'wireshark_ofp',
   :path => 'site-cookbooks/wireshark_ofp'
